Add docker-image-shipping repo
memgraph/memgraph-platform pull request #39
Opened 2023-02-15 13:48 UTC by brunos252

2023-02-15 14:33 UTC, as51340 commented on docker-image-build/platform_img/create_platform_img.sh
> +memgraph_and_lab=${5-false}
What does `5-false` mean?

2023-02-15 14:34 UTC, as51340 requested changes
If an option is to add empty.txt to .gitignore, I would do that. Other things look good to me

2023-02-15 15:33 UTC, brunos252 commented
There are still comments leftover here: https://github.com/memgraph/docker-image-shipping/pull/1
Which I didn't currently have time to address

2023-02-15 15:35 UTC, brunos252 commented
> If an option is to add empty.txt to .gitignore, I would do that. Other things look good to me

I am not sure why we even have these files? If we can add them to gitignore, we can also delete them?

2023-02-15 15:39 UTC, Josipmrden reviewed
Seems okay, just change the branch name to airtable task like we do in the rest of the repositories (T...-FL-...)

2023-02-15 15:39 UTC, Josipmrden commented on docker-image-build/memgraph_deb/build.sh
> +cpack -G DEB --config "../CPackConfig.cmake"
newline

2023-02-15 22:00 UTC, as51340 commented
> > If an option is to add empty.txt to .gitignore, I would do that. Other things look good to me
> 
> I am not sure why we even have these files? If we can add them to gitignore, we can also delete them? @as51340

Yes I am also not sure but I think noting bad will happen if we delete them.

2023-02-15 22:01 UTC, as51340 approved these changes

2023-02-16 11:52 UTC, brunos252 commented
> Seems okay, just change the branch name to airtable task like we do in the rest of the repositories (T...-FL-...)

@Josipmrden unfortunately, to rename a remote branch I need to create a new one and delete this one, which includes making a new PR. Let me know if that is what you want me to do. Meanwhile I renamed the PR to match our format.

2023-02-17 06:24 UTC, antepusic approved these changes
I see that my suggestions in the [initial PR](https://github.com/memgraph/docker-image-shipping/pull/1) were accepted; everything looks good to me now!

2023-03-05 22:10 UTC, Josipmrden commented
Added some cleaning to the scripts and how the images are generated. I hope it will result in a much faster build and less commands to generate custom images.

We still need to figure out how to decrease MAGE build time since it seems it's taking 4 hours.

2023-03-05 22:10 UTC, Josipmrden commented
Re-requesting review again, on my changes @as51340 @antepusic @antoniofilipovic @brunos252

2023-03-06 09:58 UTC, as51340 commented on scripts/build_mage_img.sh
> +cp "${CURR_DIR}/resources/memgraph-${deb_name}_amd64.deb" "${MAGE_DIR}/memgraph-${deb_name}_amd64.deb"
I would at the beginning that MAGE_DIR is created if doesn't exist just to avoid possible errors.

2023-03-06 10:00 UTC, as51340 commented on scripts/build_mage_img.sh
> +docker buildx build --target prod --platform=linux/amd64 -t ${image_name} --build-arg TARGETARCH=${deb_name}_amd64 -f ${MAGE_DIR}/Dockerfile.release .
What about `cugraph`?

2023-03-06 10:03 UTC, as51340 commented on scripts/_build_mg.sh
> +cmake -DCMAKE_BUILD_TYPE=Release .. && make -j4 memgraph && make -j4 mgconsole
I would extract num of threads as a command line argument.

2023-03-06 10:06 UTC, as51340 commented on scripts/build_deb.sh
> +docker stop meme-build || true && docker rm meme-build || true
Can you explain what this line does? I am not sure what is `meme-build`.

2023-03-06 10:08 UTC, as51340 commented on scripts/README.md
> +The script stores all `.deb` files in the `output_debian` folder.
This is changed now right?

2023-03-06 10:10 UTC, as51340 requested changes
Just small comments + I think README is not updated

2023-04-04 12:15 UTC, antepusic requested changes

2023-04-04 12:15 UTC, antepusic commented on scripts/README.md
> +1. Store the memgraph Debian package file in the `memgraph_deb_files` folder with the exact name: `memgraph-{deb_name}_amd64.deb` and run the script with the following command:
Either change the folder name to `resources` or update the script to use `memgraph_deb_files`

2023-04-04 12:15 UTC, antepusic commented on scripts/build_mage_img.sh
> +rm -rf ${MAGE_DIR}
When I ran the script, it didn’t save the .tar.gz file anywhere - check this part more closely

2023-04-24 15:08 UTC, antoniofilipovic commented on scripts/build_deb.sh
> +git clone -b $branch_name https://github.com/memgraph/memgraph.git
This fails if you don't specify $branch_name and script just continues to work.

2023-06-24 16:54 UTC, gitbuda commented on scripts/build_mage_img.sh
> +docker buildx build --target prod --platform=linux/amd64 -t ${image_name} --build-arg TARGETARCH=${deb_name}_amd64 -f ${MAGE_DIR}/Dockerfile.release .
we add later

2023-07-23 13:29 UTC, merged